### PR TITLE
Add support for YCbCrSubsampleRatio411 and YCbCrSubsampleRatio410

### PR DESCRIPTION
**Pull request by charlievieth**
This commit adds support for the YCbCrSubsampleRatio411 and
YCbCrSubsampleRatio410 subsample ratios introduced in Go 1.5
and maintains backwards compatibility with older versions of
Go.

### CODE REVIEW

**Comment by unixpickle** [comment]
How is this different than #39 ?

**Comment by charlievieth** [comment]
@unixpickle Thanks for the reminder, that was so long ago I forgot I even did that and was just trying to help with https://github.com/nfnt/resize/pull/51.

Took a look at https://github.com/nfnt/resize/pull/39 and the only delta is that pre-go15 stuff is now in files named `*_go14.go` (which is good, because they only exist for backwards compatibility) and the tests in this PR maintain backwards compatibility in a simpler way (the current test file remains `ycc_test.go` - new rations are added in `ycc_go15_test.go`).

Also, it appears Travis does not like this commit - likely due to test file `ycc_test_go15.go` not being named `ycc_go15_test.go` - thats now fixed.

**Comment by charlievieth** [comment]
Closing, superseded by https://github.com/nfnt/resize/pull/39.

**Comment by charlievieth** [comment]
Closing, superseded by https://github.com/nfnt/resize/pull/39.

**Pull request closed without merging**
